{ config, pkgs, ... }:

{
  # Dashboards. Bound to all interfaces and exposed on the LAN (firewall port
  # 3000) and over Tailscale. Prometheus + Loki datasources are provisioned.
  services.grafana = {
    enable = true;
    settings = {
      server = {
        http_addr = "0.0.0.0";
        http_port = 3000;
        domain = "${config.networking.hostName}.local";
      };
      analytics.reporting_enabled = false;
      # 26.05 dropped the built-in default; read a host-generated key so no
      # secret is committed. Generated by the grafana-secret-key service below.
      security.secret_key = "$__file{/var/lib/grafana/secret_key}";
    };
    provision = {
      enable = true;
      datasources.settings.datasources = [
        {
          name = "Prometheus";
          type = "prometheus";
          access = "proxy";
          url = "http://127.0.0.1:${toString config.services.prometheus.port}";
          isDefault = true;
          uid = "prometheus";
        }
        {
          name = "Loki";
          type = "loki";
          access = "proxy";
          url = "http://127.0.0.1:3100";
          uid = "loki";
        }
      ];
      # Any *.json dropped into ./dashboards is auto-provisioned on rebuild.
      dashboards.settings.providers = [
        {
          name = "default";
          options.path = ./dashboards;
        }
      ];
    };
  };

  networking.firewall.allowedTCPPorts = [ 3000 ];

  # Generate Grafana's secret_key on first boot if absent, so it stays out of
  # the repo. Runs before grafana.service and persists across rebuilds.
  systemd.services.grafana-secret-key = {
    wantedBy = [ "multi-user.target" ];
    before = [ "grafana.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      key=/var/lib/grafana/secret_key
      if [ ! -f "$key" ]; then
        mkdir -p /var/lib/grafana
        ${pkgs.openssl}/bin/openssl rand -hex 32 > "$key"
        chown grafana:grafana "$key"
        chmod 600 "$key"
      fi
    '';
  };
}
