# Intentionally minimal. This is normally generated by `nixos-generate-config`,
# but the Pi's hardware specifics are hand-maintained in configuration.nix
# instead (boot.initrd.availableKernelModules for the USB3/T7 boot chain, the
# `fileSystems."/"` root by-label, extlinux loader). Keeping those in one place
# avoids a generated file that would duplicate — and drift from — that config.
#
# If you ever regenerate this with `nixos-generate-config`, de-dupe the
# fileSystems/boot entries it emits against configuration.nix before committing.
{ ... }:

{ }
