on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v5

      - name: Show flake
        run: nix flake Show

      - name: Check flake evaluation
        run: nix flake check --keep-going
