on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Show flake
        run: nix flake show

      - name: Check flake evaluation
        run: nix flake check --keep-going
