# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * 0"

on: push

permissions:
  contents: "write"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "${GITHUB_ACTOR}"

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v5

      - name: Setup caching
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update flake
        run: nix flake update --commit-lock-file

      - name: Check flake
        run: nix flake check --all-systems

      # - run: git push
